"""Exportable operator reports (offline template + optional LLM summary hook)."""

from __future__ import annotations

from typing import Any


def build_operator_report(
    *,
    sessions: list[dict[str, Any]],
    timeline: list[dict[str, Any]],
    heatmap: dict[str, Any],
    anomalies: dict[str, Any] | None = None,
    title: str = "SquidC5 Operator Report",
) -> dict[str, Any]:
    active = [s for s in sessions if s.get("status") == "active"]
    lines = [
        f"# {title}",
        "",
        f"- Active sessions: {len(active)}",
        f"- Timeline events: {len(timeline)}",
        f"- Heatmap hosts: {len((heatmap or {}).get('by_host') or {})}",
        "",
        "## Sessions",
    ]
    for s in active[:50]:
        lines.append(
            f"- `{s.get('id','')[:12]}` kind={s.get('kind')} host={s.get('hostname') or s.get('remote_addr')}"
        )
    lines.append("")
    lines.append("## Recent actions (ATT&CK-tagged)")
    for e in timeline[:30]:
        attack = ",".join(e.get("attack") or []) or "-"
        lines.append(f"- {e.get('action')} actor={e.get('actor')} attack=[{attack}]")
    if anomalies:
        lines.append("")
        lines.append("## Anomaly findings")
        for f in anomalies.get("findings") or []:
            lines.append(f"- [{f.get('severity')}] {f.get('code')}: {f.get('detail')} → {f.get('suggest')}")
    lines.append("")
    lines.append("_Authorized use only. Generated by SquidC5._")
    md = "\n".join(lines)
    return {
        "title": title,
        "markdown": md,
        "stats": {
            "active_sessions": len(active),
            "timeline_events": len(timeline),
        },
    }
